/**
 * YouLend Third Party Instant Settlement API
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InstantSettlementView model module.
 * @module model/InstantSettlementView
 * @version v1.0
 */
class InstantSettlementView {
    /**
     * Constructs a new <code>InstantSettlementView</code>.
     * Model for viewing details of an Instant Settlement
     * @alias module:model/InstantSettlementView
     */
    constructor() { 
        
        InstantSettlementView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InstantSettlementView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InstantSettlementView} obj Optional instance to populate.
     * @return {module:model/InstantSettlementView} The populated <code>InstantSettlementView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InstantSettlementView();

            if (data.hasOwnProperty('instantSettlementId')) {
                obj['instantSettlementId'] = ApiClient.convertToType(data['instantSettlementId'], 'String');
            }
            if (data.hasOwnProperty('instantSettlementNumber')) {
                obj['instantSettlementNumber'] = ApiClient.convertToType(data['instantSettlementNumber'], 'Number');
            }
            if (data.hasOwnProperty('lenderName')) {
                obj['lenderName'] = ApiClient.convertToType(data['lenderName'], 'String');
            }
            if (data.hasOwnProperty('borrowerName')) {
                obj['borrowerName'] = ApiClient.convertToType(data['borrowerName'], 'String');
            }
            if (data.hasOwnProperty('currencyISOCode')) {
                obj['currencyISOCode'] = ApiClient.convertToType(data['currencyISOCode'], 'String');
            }
            if (data.hasOwnProperty('settlementCycleLengthDay')) {
                obj['settlementCycleLengthDay'] = ApiClient.convertToType(data['settlementCycleLengthDay'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the Instant Settlement Id
 * @member {String} instantSettlementId
 */
InstantSettlementView.prototype['instantSettlementId'] = undefined;

/**
 * Gets or sets the Instant Settlement number
 * @member {Number} instantSettlementNumber
 */
InstantSettlementView.prototype['instantSettlementNumber'] = undefined;

/**
 * Gets or sets the lender name
 * @member {String} lenderName
 */
InstantSettlementView.prototype['lenderName'] = undefined;

/**
 * Gets or sets the borrower name
 * @member {String} borrowerName
 */
InstantSettlementView.prototype['borrowerName'] = undefined;

/**
 * Gets or sets the currency ISO code
 * @member {String} currencyISOCode
 */
InstantSettlementView.prototype['currencyISOCode'] = undefined;

/**
 * Gets or sets the settlement cycle length (number of days)
 * @member {Number} settlementCycleLengthDay
 */
InstantSettlementView.prototype['settlementCycleLengthDay'] = undefined;






export default InstantSettlementView;

