/**
 * YouLend Third Party Instant Settlement API
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyInstantsettlementApiClient);
  }
}(this, function(expect, YlThirdPartyInstantsettlementApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyInstantsettlementApiClient.CreateInstantSettlementTransactionModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateInstantSettlementTransactionModel', function() {
    it('should create an instance of CreateInstantSettlementTransactionModel', function() {
      // uncomment below and update the code to test CreateInstantSettlementTransactionModel
      //var instane = new YlThirdPartyInstantsettlementApiClient.CreateInstantSettlementTransactionModel();
      //expect(instance).to.be.a(YlThirdPartyInstantsettlementApiClient.CreateInstantSettlementTransactionModel);
    });

    it('should have the property transactionReferences (base name: "transactionReferences")', function() {
      // uncomment below and update the code to test the property transactionReferences
      //var instane = new YlThirdPartyInstantsettlementApiClient.CreateInstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property currencyISOCode (base name: "currencyISOCode")', function() {
      // uncomment below and update the code to test the property currencyISOCode
      //var instane = new YlThirdPartyInstantsettlementApiClient.CreateInstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property totalSettlementAmount (base name: "totalSettlementAmount")', function() {
      // uncomment below and update the code to test the property totalSettlementAmount
      //var instane = new YlThirdPartyInstantsettlementApiClient.CreateInstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property transactionDate (base name: "transactionDate")', function() {
      // uncomment below and update the code to test the property transactionDate
      //var instane = new YlThirdPartyInstantsettlementApiClient.CreateInstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

  });

}));
