/**
 * YouLend Third Party Instant Settlement API
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyInstantsettlementApiClient);
  }
}(this, function(expect, YlThirdPartyInstantsettlementApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InstantSettlementTransactionModel', function() {
    it('should create an instance of InstantSettlementTransactionModel', function() {
      // uncomment below and update the code to test InstantSettlementTransactionModel
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be.a(YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel);
    });

    it('should have the property instantSettlementId (base name: "instantSettlementId")', function() {
      // uncomment below and update the code to test the property instantSettlementId
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property instantSettlementTransactionNumber (base name: "instantSettlementTransactionNumber")', function() {
      // uncomment below and update the code to test the property instantSettlementTransactionNumber
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property dateCreated (base name: "dateCreated")', function() {
      // uncomment below and update the code to test the property dateCreated
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property dateFunded (base name: "dateFunded")', function() {
      // uncomment below and update the code to test the property dateFunded
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property dateRepaid (base name: "dateRepaid")', function() {
      // uncomment below and update the code to test the property dateRepaid
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property currentAmount (base name: "currentAmount")', function() {
      // uncomment below and update the code to test the property currentAmount
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property fundedAmount (base name: "fundedAmount")', function() {
      // uncomment below and update the code to test the property fundedAmount
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new YlThirdPartyInstantsettlementApiClient.InstantSettlementTransactionModel();
      //expect(instance).to.be();
    });

  });

}));
