/**
 * YouLend Third Party Instant Settlement API
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import CreateInstantSettlementTransactionModel from './model/CreateInstantSettlementTransactionModel';
import InstantSettlementTransactionModel from './model/InstantSettlementTransactionModel';
import InstantSettlementView from './model/InstantSettlementView';
import InstantSettlementApi from './api/InstantSettlementApi';


/**
* Through_this_API_you_can_can_create_Instant_Settlement_transactions_with_YouLend.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var YlThirdPartyInstantsettlementApiClient = require('index'); // See note below*.
* var xxxSvc = new YlThirdPartyInstantsettlementApiClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new YlThirdPartyInstantsettlementApiClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new YlThirdPartyInstantsettlementApiClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new YlThirdPartyInstantsettlementApiClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The CreateInstantSettlementTransactionModel model constructor.
     * @property {module:model/CreateInstantSettlementTransactionModel}
     */
    CreateInstantSettlementTransactionModel,

    /**
     * The InstantSettlementTransactionModel model constructor.
     * @property {module:model/InstantSettlementTransactionModel}
     */
    InstantSettlementTransactionModel,

    /**
     * The InstantSettlementView model constructor.
     * @property {module:model/InstantSettlementView}
     */
    InstantSettlementView,

    /**
    * The InstantSettlementApi service constructor.
    * @property {module:api/InstantSettlementApi}
    */
    InstantSettlementApi
};
